name: CI-CD Docker Pipeline Trivy

on:
  push:
    branches:
      - trivy

env:
  IMAGE_NAME: ci-html
  IMAGE_TAG: 1.0.1

jobs:

  # ===============================
  # JOB 1 - BUILD & SCAN TRIVY
  # ===============================
  ci-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image locally
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          severity: CRITICAL
          exit-code: 0 # Permet de ne pas bloquer le pipeline s'il y a des vulnérabilités dans l'image de base
          vuln-type: os,library

  # ===============================
  # JOB 2 - CD : DEPLOY SIMULATION
  # ===============================
  deploy:
    needs: ci-and-scan
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Simulation
        run: |
          echo "Déploiement de l'image $IMAGE_NAME:$IMAGE_TAG réussi avec succès !"